version: '3.7'
services:
  telegraf:
    image: telegraf
    depends_on:
      - "influxdb"
    configs:
    - source: telegraf-conf
      target: /etc/telegraf/telegraf.conf
    ports:
    - 8186:8186
  influxdb:
    image: influxdb:1.8
    ports:
    - 8086:8086
  chronograf:
    image: chronograf
    ports:
    - 8888:8888
    depends_on:
      - "influxdb"
    command: ["chronograf", "--influxdb-url=http://influxdb:8086"]
  kapacitor:
    image: kapacitor
    environment:
    - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
configs:
  telegraf-conf:
    file: ./telegraf.conf
